### ISSUE TITLE
mt.randomstandardnormal errors with logic variables

### ISSUE THREAD

**Issue by josephwillard** [pymc-devs/symbolic-pymc#53]
The following snippet,

```
with graph_mode():
    mt.randomstandardnormal(mean=0, stddev=1, shape=(1000, ), dtype=tf.float32)
```
produces the expected output,

```
TFlowMetaTensor(
  dtype=tf.float32,
  op=TFlowMetaOp(
    op_def=TFlowMetaOpDef(RandomStandardNormal),
    node_def=TFlowMetaNodeDef(
      op='RandomStandardNormal',
      name='RandomStandardNormal_2',
      attr=OrderedDict([('dtype', 'float32'),
                   ('seed', TFlowMetaConstant( )),
                   ('seed2', TFlowMetaConstant( ))])),
    inputs=(TFlowMetaConstant( ),),
    name='RandomStandardNormal_2'),
  value_index=0,
  shape=TFlowMetaTensorShape( dims=(1000,)),
  name='RandomStandardNormal_2:0')
```

However, by adding a logic variable,

```
with graph_mode():
    mt.randomstandardnormal(mean=0, stddev=1, shape=(1000, ), dtype=tf.float32, name=var())
```

gives the following error,

```
~/git_projects/symbolic-pymc/symbolic_pymc/tensorflow/meta.py in __call__(self, *args, **kwargs)
    318         op_mt = TFlowMetaOp(self, node_def, op_input_args, name=op_name)
    319 
--> 320         res_var = op_mt.default_output
    321 
    322         return res_var

~/git_projects/symbolic-pymc/symbolic_pymc/tensorflow/meta.py in default_output(self)
    527             return self._default_output
    528 
--> 529         mt_outs = self.outputs
    530 
    531         if isvar(mt_outs):

~/git_projects/symbolic-pymc/symbolic_pymc/tensorflow/meta.py in outputs(self)
    510                 ),
    511             )
--> 512             for i, o in enumerate(out_types_mt)
    513         )
    514 

~/git_projects/symbolic-pymc/symbolic_pymc/tensorflow/meta.py in <genexpr>(.0)
    510                 ),
    511             )
--> 512             for i, o in enumerate(out_types_mt)
    513         )
    514 

TypeError: 'NoneType' object is not callable
```

**Comment by brandonwillard** [comment]
It's running into trouble when it attempts to [synthesize the output of the meta operation](https://github.com/pymc-devs/symbolic-pymc/blob/master/symbolic_pymc/tensorflow/meta.py#L484) (i.e. the `TFlowMetaOp`).

There are two routes to obtain a meta object for the output of a backend's operation: 
1. create or use the underlying backend output object and convert that to a meta object, or 
2. construct the meta output directly by hand using only meta types and whatever info we can get about the output of the backend operation.

The former is generally simpler and much more precise (in that all the meta fields will be filled in with the same type of information that the backend would use/expect), but it&mdash;naturally&mdash;requires potentially expensive backend graph construction steps.  Also, this approach is only possible when all the meta object's inputs are "reifiable" (i.e. can be converted to valid base objects).

The meta-only approach will try to guess the fields it's not given (e.g. what the dtype of an operation's output is), or it will default to logic variables for those values when it can't.


Anyway, the part that's failing involves a step in the meta-only approach that tries to determine the type of object output by an `OpDef` using information from its `output_arg` field (in `protobuf` format).  [The only type currently recognized for that field is the protobuf type corresponding to a `tf.Tensor` (signified by the character `"T"`)](https://github.com/pymc-devs/symbolic-pymc/blob/master/symbolic_pymc/tensorflow/meta.py#L243).  However, `RandomStandardNormal` seems to only provide a `dtype`, which I assume represents the `dtype` of the *`tf.Tensor` it outputs.

We simply need to add that case.
