### ISSUE TITLE
Improve performance of basic miniKanren goals

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/symbolic-pymc#58]
[Looking at some basic profiling results for our graph goals in `kanren`](https://gist.github.com/brandonwillard/eabb0aa0964c213af8e5050db475f4ab), the `unique` step introduced by the current implementations of [`lany`](https://github.com/logpy/logpy/blob/master/kanren/core.py#L121) and [`lall`](https://github.com/logpy/logpy/blob/master/kanren/core.py#L41) (or indirectly via `conde`, `condeseq`, etc.) is unnecessary and apparently costly, so we should provide replacements that do not use it.

Likewise, we'll probably need to implement constraints in a more direct way (e.g. change the state to include constraint mappings and check them during unification [[paper](https://arxiv.org/abs/1701.00633)]), since `kanren`'s approach via emulation of macro-like S-expression evaluation (e.g. `evalt`, `earlyeval`, `find_fixed_point`) and raising/catching `EarlyGoalError`s  is also costly and unnecessarily complex.

This is related to&mdash;but more widely applicable and distinct from&mdash;issue #27.

**Comment by rpgoldman** [comment]
Is this because you are using the equivalent of `setof` where `bagof` would be sufficient?

**Comment by brandonwillard** [comment]
Well, it goes a little further back than even that; miniKanren results are ultimately pulled from generator streams (produced by goals), and `unique`/sets/bags of those streams are really just a convenience that only applies in some situations!  I do think that a bag would be more appropriate, though, because losing that count information is pretty bad.

In general, miniKanren has no problem returning duplicate results.  As a matter of fact, most (perhaps even all) published miniKanren implementations are *supposed to* produce duplicates&mdash;when the goals intentionally generate them, of course.

In our case, we're primarily interested in the first output from our fixed-point graph reduction relations/goals, so we don't even care about duplicates; however, if we were to use the entire result set, it _would_ include quite a few duplicates (especially when the reduction/rewrite rules are confluent), so `unique` and/or conversion to a set might be useful as a quick&mdash;and costly&mdash;post-processing clean-up.  

Really, for efficiency, duplication through known properties like confluence are better addressed at the goal/relation-level.  For instance, do not produce sub-goals for more than one path when you know they'll all necessarily produce the same result (e.g. [using `condp`](https://github.com/pymc-devs/symbolic-pymc/issues/6#issue-417974266) and perhaps some fancy [rewrite completion](https://github.com/brandonwillard/mk-rewrite-completion)).

**Comment by rpgoldman** [comment]
I think I see, yes -- if you know that multiple rules are mutually exclusive, you can use something that has the effect of Prolog's cut (`!`) to prune the search space.
In Prolog, where the rules are found in a database, you can also make things more efficient by ensuring that only the rule that matches the precise goal will be retrieved, pushing more of the cost into the database lookup, which is cheap.  But I don't know if what you are doing is *that* Prolog-y.

**Comment by brandonwillard** [comment]
Exactly!  The whole Prolog `cut` concept is spot on, and miniKanren is also directly affected by much of these same concerns.  What we're doing in/with miniKanren is essentially logic programming in the same sense as Prolog.  The implementation details and some guiding principles/concepts can differ quite a bit, though.

**Comment by brandonwillard** [comment]
This has been addressed by the new `kanren` package.
