### ISSUE TITLE
Set up CI and Black

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/symbolic-pymc#7]
We need to set up Travis/CircleCI/etc. as well as `flake8` and [`black`](https://github.com/ambv/black).

**Comment by ericmjl** [comment]
*and 😸

**Comment by brandonwillard** [comment]
Fixed.

**Comment by ericmjl** [comment]
😹 😂

**Comment by canyon289** [comment]
I'm not strongly opinionated but any reason not to choose travisci and pylint to stay consistent with pymc3/4 and arviz?

**Comment by brandonwillard** [comment]
No, no reason; Travis and `pylint` (and `black`) it is.
